---
title: "R Notebook"
output: html_notebook
---

```{r}
# I'm using readxl because it has no external dependencies
library(readxl)
library(reshape2)
#library(plyr) Obsolete package
library(data.table)
library(writexl)

pwd <- getwd() # sets the current working directory
pwd
```
```{r}
filepath <- paste(pwd, "/Data - Survey Monkey Output Edited.xlsx", sep="") # Make sure you fix this separator, it's a space by default
filepath
```

```{r}
data_import <- read_excel(filepath , sheet = "Edited_Data")
data_import
```
```{r}
dataset_modified <- data.frame(data_import) # Make a copy of the dataframe

dataset_modified # R seems to add "." to my column names
```
```{r}
columns_to_drop <- c('Start.Date', 'End.Date', 'Email.Address', 'First.Name', 'Last.Name', 'Custom.Data.1')
columns_to_drop
```
```{r}
dataset_modified <- dataset_modified[ , ! names(dataset_modified) %in% columns_to_drop] 
dataset_modified # More methods: https://www.youtube.com/watch?v=yhdxuFNvHxU
```

```{r}
id_vars <- colnames(dataset_modified)[1:8] # Install the reshape2 package, R uses 1 based indexing
id_vars
```

```{r}
dataset_melted <- melt(dataset_modified, id=id_vars, variable.name = "Question.+.Subquestion", value.name = "Answer")
dataset_melted
```
```{r}
questions_import <- read_excel(filepath, sheet="Question_R")
questions_import
```
```{r}
questions <- data.frame(questions_import)
questions
```
```{r}
questions <- questions[ , ! names(questions) %in% c("Raw.Question", "Raw.Subquestion", "Subquestion")]
questions
```


```{r}

dataset_merged <- merge(x=dataset_melted, y=questions, by.x ="Question.+.Subquestion", by.y = "Question...Subquestion", all.x=TRUE) # https://stackoverflow.com/questions/1299871/how-to-join-merge-data-frames-inner-outer-left-right

dataset_merged
```
```{r}
respondents <- dataset_merged[! is.na(dataset_merged$Answer),]
respondents
```

```{r}
DT <- data.table(respondents)
respondents <- DT[, .(number_of_distinct_answers = length(unique(Respondent.ID))), by = Question]

respondents
```

```{r}
dataset_merged_two <- merge(x=dataset_merged, y=respondents, by="Question", all.x = TRUE)
dataset_merged_two
```

```{r}
same_answer <- dataset_merged[! is.na(dataset_merged$Answer),]

DT_one <- data.table(same_answer)
same_answer <- DT_one[, .(number_of_distinct_answers_two = length(unique(Respondent.ID))), by = c('Question.+.Subquestion', 'Answer')]
same_answer
```

```{r}
dataset_merged_three <- merge(x=dataset_merged_two, y=same_answer, by=c('Question.+.Subquestion', 'Answer'), all.x = TRUE)
dataset_merged_three
```

```{r}
colnames(dataset_merged_three)
```

```{r}
names(dataset_merged_three)[names(dataset_merged_three) == "Identify.which.division.you.work.in....Response"] <- "Division"

names(dataset_merged_three)[names(dataset_merged_three) == "Identify.which.division.you.work.in....Other..please.specify."] <- "Division Other"

names(dataset_merged_three)[names(dataset_merged_three) == "Which.of.the.following.best.describes.your.position.level....Response"] <- "Position"

names(dataset_merged_three)[names(dataset_merged_three) == "Which.generation.are.you.apart.of....Response"] <- "Generation"

names(dataset_merged_three)[names(dataset_merged_three) == "Please.select.the.gender.in.which.you.identify....Response"] <- "Gender"

names(dataset_merged_three)[names(dataset_merged_three) == "Which.duration.range.best.aligns.with.your.tenure.at.your.company....Response"] <- "Tenure"

names(dataset_merged_three)[names(dataset_merged_three) == "Which.of.the.following.best.describes.your.employment.type....Response"] <- "EmploymentType"

names(dataset_merged_three)[names(dataset_merged_three) == "number_of_distinct_answers"] <- "Respondents"

names(dataset_merged_three)[names(dataset_merged_three) == "number_of_distinct_answers_two"] <- "SameAnswer"

dataset_merged_three
```

```{r}
write_xlsx(dataset_merged_three, paste(pwd , "/Final_Output_R.xlsx", sep=""))
```

